name: serec
channels:
  - pytorch
  - dglteam
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.2=py38heb32a55_1
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dgl=0.7.2=py38_0
  - dgl-cuda11.3=0.7.2=py38_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuv=1.40.0=h7b6447c_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - networkx=2.6.3=pyhd3eb1b0_0
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy-base=1.21.2=py38h79a1101_0
  - openssl=1.1.1l=h7f8727e_0
  - pandas=1.3.4=py38h8c16a72_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - charset-normalizer==2.0.9
    - idna==3.3
    - joblib==1.1.0
    - llvmlite==0.37.0
    - numba==0.54.1
    - numpy==1.20.3
    - requests==2.26.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - sklearn==0.0
    - threadpoolctl==3.0.0
    - urllib3==1.26.7
prefix: /home/gjy/anaconda3/envs/serec
